var remoteUrls = [
    { viewName:"testAPI",remoteUrl:'/remote/EventApi/'},
    { viewName:"treeViewApi",remoteUrl:'/remote/TreeViewApi/'},
    { viewName:"userApi",remoteUrl:'/remote/UserApi/'},
    { viewName:"monitorViews",remoteUrl:'/remote/MonitorApi/'},
    { viewName:"deviceViews",remoteUrl:'/remote/DeviceApi/'},
    { viewName:"websiteViews",remoteUrl:'/remote/WebsiteApi/'},
    { viewName:"userMessageViews",remoteUrl:'/remote/UserMessageApi/'},
    { viewName:"managerViews",remoteUrl:'/remote/ManagerApi/'},
    { viewName:"eventViews",remoteUrl:'/remote/EventApi/'},
    { viewName:"serviceNoteViews",remoteUrl:'/remote/ServiceNoteApi/'},
    { viewName:"performImageViews",remoteUrl:'/remote/PerformImageApi/'},
    { viewName:"networkViews",remoteUrl:'/remote/NetworkApi/'},
    { viewName:"middlewareViews",remoteUrl:'/remote/MiddlewareApi/'},
    { viewName:"mwNginxViews",remoteUrl:'/remote/MwNginxApi/'},
    { viewName:"mwTomcatViews",remoteUrl:'/remote/MwTomcatApi/'},
    { viewName:"mwApacheViews",remoteUrl:'/remote/MwApacheApi/'},
    { viewName:"mwIisViews",remoteUrl:'/remote/MwIisApi/'},
    { viewName:"shortcutCmdViews",remoteUrl:'/remote/ShortcutCmdApi/'},
    { viewName:"bootpoViews",remoteUrl:'/remote/BootpoApi/'},
    { viewName:"thresholdViews",remoteUrl:'/remote/ThresholdApi/'},
    { viewName:"feedback",remoteUrl:'/remote/feedBackInfoApi/'},
    { viewName:"reportApi",remoteUrl:'/remote/ReportApi/'},
    { viewName:"messageApi",remoteUrl:'/remote/MessageApi/'},
    { viewName:"vmhostViews",remoteUrl:'/remote/VmhostApi/'},
    { viewName:"locationViews",remoteUrl:'/remote/LocationApi/'},
    { viewName:"billingViews",remoteUrl:'/remote/BillingApi/'},
    { viewName:"customerMapViews",remoteUrl:'/remote/CustomerMapApi/'},
    { viewName:"swglViews",remoteUrl:'/remote/SwglApi/'},
    { viewName:"topicViews",remoteUrl:'/remote/TopicApi/'}

];